### ISSUE TITLE
Is there a full demo???  This doesn't seem to work I tested it 10 times and it doesn't work I even think it's just a backdoor, the payload exe does nothing when clicked

### ISSUE THREAD

**Issue by kk159963** [Kammerflimmern/discord-stealer-token-grabber#3]
Is there a full demo???

This doesn't seem to work I tested it 10 times and it doesn't work
I even think it's just a backdoor, the payload exe does nothing when clicked

**Comment by Kammerflimmern** [comment]
Are you maybe missing a dependency?

**Comment by VemV12** [comment]
i think you're right and it indeed is a payload
